#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Train the NailGlow V2 two-stage questionnaire model.

Input is a JSON object on stdin. It may contain ``samples`` directly or a
``datasetPath`` pointing to the deterministic demo dataset generated by
``generate_demo_score_data.py``.
"""

from __future__ import annotations

import json
import math
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import joblib
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.model_selection import GroupKFold

from score_model_framework import (
    MODEL_SCHEMA_VERSION,
    MORPHOLOGY_TARGETS,
    SCORE_TARGETS,
    STYLE_FEATURE_COLS,
    V2_EXCLUDED_BASE_FEATURES,
    aggregate_overall,
    compatibility_columns,
    compatibility_row,
    heuristic_morphology,
    learn_overall_weights,
    ndcg_at_k,
    normalize_row,
    percentile_stats,
    spearman_correlation,
)
from score_model_predict import (
    DEFAULT_FEATURE_COLS,
    ROOT,
    bool_payload,
    image_features,
    load_style_features,
)


BASE_FEATURE_COLS = tuple(
    column for column in DEFAULT_FEATURE_COLS
    if column not in V2_EXCLUDED_BASE_FEATURES
)
HAND_FEATURE_COLS = tuple(
    column for column in BASE_FEATURE_COLS if not column.startswith("style_")
)
COMPATIBILITY_FEATURE_COLS = compatibility_columns(BASE_FEATURE_COLS)


def read_payload() -> dict:
    return json.loads(sys.stdin.read() or "{}")


def resolve_path(value) -> Path:
    path = Path(value or "").expanduser()
    if not path.is_absolute():
        path = (ROOT / path).resolve()
    return path


def load_samples(payload: dict) -> tuple[list[dict], dict]:
    dataset_path = payload.get("datasetPath")
    if dataset_path:
        dataset = json.loads(resolve_path(dataset_path).read_text(encoding="utf-8"))
        if isinstance(dataset, list):
            return dataset, {"source": str(dataset_path)}
        return list(dataset.get("samples") or []), dict(dataset.get("metadata") or {})
    return list(payload.get("samples") or []), dict(payload.get("datasetMetadata") or {})


def numeric_mapping(value, names, fallback=None) -> dict[str, float]:
    source = value if isinstance(value, dict) else {}
    result: dict[str, float] = {}
    for name in names:
        raw = source.get(name)
        if raw is None and fallback is not None:
            raw = fallback
        if raw is None:
            raise ValueError(f"missing target: {name}")
        result[name] = max(0.0, min(100.0, float(raw)))
    return result


def sample_features(sample: dict, use_mediapipe=True) -> dict[str, float] | None:
    precomputed = isinstance(sample.get("features"), dict)
    if precomputed:
        features = {
            column: float(sample["features"].get(column, 0.0))
            for column in BASE_FEATURE_COLS
        }
    else:
        image_path = resolve_path(sample.get("imagePath"))
        if not image_path.exists():
            return None
        features = image_features(image_path, use_mediapipe=use_mediapipe)
        if use_mediapipe and float(features.get("mediapipe_detected", 0.0)) < 0.5:
            return None

    style_code = sample.get("styleCode") or "nail_01"
    style = load_style_features(style_code)
    features.update({key: float(style[key]) for key in STYLE_FEATURE_COLS})
    return {column: float(features.get(column, 0.0)) for column in BASE_FEATURE_COLS}


def prepare_rows(samples: list[dict], use_mediapipe: bool):
    rows: list[dict[str, float]] = []
    morphology_targets: list[list[float]] = []
    score_targets: list[list[float]] = []
    overall_targets: list[float] = []
    groups: list[str] = []
    response_counts: list[int] = []

    for index, sample in enumerate(samples):
        features = sample_features(sample, use_mediapipe=use_mediapipe)
        if not features:
            continue
        fallback_score = sample.get("targetScore")
        targets = numeric_mapping(sample.get("targets"), SCORE_TARGETS, fallback_score)
        morphology = numeric_mapping(
            sample.get("morphologyTargets") or heuristic_morphology(features),
            MORPHOLOGY_TARGETS,
        )
        overall = sample.get("overallScore")
        if overall is None:
            overall = float(np.mean([targets[name] for name in SCORE_TARGETS]))

        rows.append(features)
        morphology_targets.append([morphology[name] for name in MORPHOLOGY_TARGETS])
        score_targets.append([targets[name] for name in SCORE_TARGETS])
        overall_targets.append(max(0.0, min(100.0, float(overall))))
        groups.append(str(sample.get("groupId") or sample.get("handId") or sample.get("imagePath") or f"sample-{index}"))
        response_counts.append(max(1, int(sample.get("ratingCount") or 1)))

    return (
        rows,
        np.asarray(morphology_targets, dtype=np.float32),
        np.asarray(score_targets, dtype=np.float32),
        np.asarray(overall_targets, dtype=np.float32),
        np.asarray(groups, dtype=object),
        response_counts,
    )


def morphology_model(seed: int) -> RandomForestRegressor:
    return RandomForestRegressor(
        n_estimators=220,
        max_depth=14,
        min_samples_leaf=2,
        max_features="sqrt",
        random_state=seed,
        n_jobs=-1,
    )


def score_model(seed: int) -> RandomForestRegressor:
    return RandomForestRegressor(
        n_estimators=320,
        max_depth=18,
        min_samples_leaf=2,
        max_features=0.72,
        random_state=seed,
        n_jobs=-1,
    )


def matrix(rows, stats, columns) -> np.ndarray:
    return np.asarray(
        [[normalize_row(row, stats, columns).get(column, 0.0) for column in columns] for row in rows],
        dtype=np.float32,
    )


def compatibility_matrix(rows, stats, morphologies) -> np.ndarray:
    values = []
    for raw, morphology_values in zip(rows, morphologies):
        normalized = normalize_row(raw, stats, BASE_FEATURE_COLS)
        morphology = {
            target: float(morphology_values[index])
            for index, target in enumerate(MORPHOLOGY_TARGETS)
        }
        transformed = compatibility_row(normalized, morphology, BASE_FEATURE_COLS)
        values.append([transformed.get(column, 0.0) for column in COMPATIBILITY_FEATURE_COLS])
    return np.asarray(values, dtype=np.float32)


def target_metrics(actual: np.ndarray, predicted: np.ndarray, names) -> dict:
    mae = mean_absolute_error(actual, predicted, multioutput="raw_values")
    rmse = np.sqrt(np.mean((actual - predicted) ** 2, axis=0))
    result = {}
    for index, name in enumerate(names):
        try:
            r2 = float(r2_score(actual[:, index], predicted[:, index]))
        except ValueError:
            r2 = 0.0
        result[name] = {
            "mae": round(float(mae[index]), 4),
            "rmse": round(float(rmse[index]), 4),
            "r2": round(r2, 4),
            "spearman": round(
                spearman_correlation(actual[:, index], predicted[:, index]), 4
            ),
        }
    return result


def cross_validate(rows, morphology_y, score_y, overall_y, groups, seed):
    unique_groups = np.unique(groups)
    if len(rows) < 12 or len(unique_groups) < 3:
        return None, None, None, {
            "available": False,
            "reason": "at least 12 rows and 3 distinct hand groups are required",
        }

    split_count = min(5, len(unique_groups))
    splitter = GroupKFold(n_splits=split_count)
    morphology_oof = np.zeros_like(morphology_y, dtype=np.float64)
    score_oof = np.zeros_like(score_y, dtype=np.float64)
    assigned = np.zeros(len(rows), dtype=bool)
    row_indices = np.arange(len(rows))

    for fold, (train_indices, test_indices) in enumerate(
        splitter.split(row_indices, score_y, groups), start=1
    ):
        fold_rows = [rows[index] for index in train_indices]
        stats = percentile_stats(fold_rows, BASE_FEATURE_COLS)
        hand_train = matrix(fold_rows, stats, HAND_FEATURE_COLS)
        hand_test = matrix([rows[index] for index in test_indices], stats, HAND_FEATURE_COLS)

        morphology_estimator = morphology_model(seed + fold)
        morphology_estimator.fit(hand_train, morphology_y[train_indices])
        morphology_train_pred = morphology_estimator.predict(hand_train)
        morphology_test_pred = morphology_estimator.predict(hand_test)
        morphology_oof[test_indices] = morphology_test_pred

        compatibility_train = compatibility_matrix(fold_rows, stats, morphology_train_pred)
        compatibility_test = compatibility_matrix(
            [rows[index] for index in test_indices], stats, morphology_test_pred
        )
        score_estimator = score_model(seed + fold)
        score_estimator.fit(compatibility_train, score_y[train_indices])
        score_oof[test_indices] = score_estimator.predict(compatibility_test)
        assigned[test_indices] = True

    if not assigned.all():
        raise RuntimeError("GroupKFold did not assign every sample")

    weights = learn_overall_weights(score_y, overall_y)
    overall_oof = np.asarray(
        [aggregate_overall(row, weights) for row in score_oof], dtype=np.float64
    )
    overall_mae = float(mean_absolute_error(overall_y, overall_oof))
    metrics = {
        "available": True,
        "method": f"GroupKFold({split_count})",
        "groupKey": "handId/groupId",
        "morphology": target_metrics(morphology_y, morphology_oof, MORPHOLOGY_TARGETS),
        "scores": target_metrics(score_y, score_oof, SCORE_TARGETS),
        "overall": {
            "mae": round(overall_mae, 4),
            "rmse": round(float(math.sqrt(np.mean((overall_y - overall_oof) ** 2))), 4),
            "r2": round(float(r2_score(overall_y, overall_oof)), 4),
            "spearman": round(spearman_correlation(overall_y, overall_oof), 4),
            "ndcgAt3": round(ndcg_at_k(groups, overall_y, overall_oof, 3), 4),
        },
    }
    return morphology_oof, score_oof, weights, metrics


def top_feature_importance(model, names, limit=24):
    values = getattr(model, "feature_importances_", None)
    if values is None:
        return []
    pairs = sorted(zip(names, values), key=lambda item: float(item[1]), reverse=True)
    return [
        {"feature": name, "importance": round(float(importance), 6)}
        for name, importance in pairs[:limit]
    ]


def backup_existing(output_path: Path, payload: dict) -> str | None:
    if not output_path.exists() or not bool_payload(payload.get("backupExisting"), False):
        return None
    backup_dir = resolve_path(payload.get("backupDir") or "models/backups")
    backup_dir.mkdir(parents=True, exist_ok=True)
    requested_name = str(payload.get("backupName") or "").strip()
    backup_name = requested_name or (
        f"{output_path.stem}_pre_v2_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}{output_path.suffix}"
    )
    backup_path = backup_dir / backup_name
    if not backup_path.exists():
        shutil.copy2(output_path, backup_path)
    return str(backup_path)


def write_json(path_value, value):
    if not path_value:
        return
    path = resolve_path(path_value)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, ensure_ascii=False, indent=2), encoding="utf-8")


def main():
    payload = read_payload()
    output_path = resolve_path(payload.get("outputPath") or "score_model.joblib")
    fallback_path = resolve_path(payload.get("fallbackModelPath") or output_path)
    use_mediapipe = bool_payload(payload.get("useMediapipe"), True)
    seed = int(payload.get("seed") or 20260827)
    samples, dataset_metadata = load_samples(payload)

    rows, morphology_y, score_y, overall_y, groups, response_counts = prepare_rows(
        samples, use_mediapipe
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        if fallback_path.exists() and fallback_path != output_path:
            shutil.copy2(fallback_path, output_path)
        result = {
            "schemaVersion": MODEL_SCHEMA_VERSION,
            "sampleCount": 0,
            "groupCount": 0,
            "validationScore": 0,
            "cvMetrics": {"available": False, "reason": "no usable samples"},
        }
        write_json(payload.get("reportPath"), result)
        print(json.dumps(result, ensure_ascii=False))
        return

    _, _, cv_weights, cv_metrics = cross_validate(
        rows, morphology_y, score_y, overall_y, groups, seed
    )
    weights = cv_weights if cv_weights is not None else learn_overall_weights(score_y, overall_y)
    stats = percentile_stats(rows, BASE_FEATURE_COLS)
    hand_x = matrix(rows, stats, HAND_FEATURE_COLS)
    morphology_estimator = morphology_model(seed)
    morphology_estimator.fit(hand_x, morphology_y)
    morphology_pred = morphology_estimator.predict(hand_x)
    compatibility_x = compatibility_matrix(rows, stats, morphology_pred)
    score_estimator = score_model(seed)
    score_estimator.fit(compatibility_x, score_y)

    created_at = datetime.now(timezone.utc).isoformat()
    training_metadata = {
        "sample_count": len(rows),
        "group_count": int(len(np.unique(groups))),
        "questionnaire_response_count": int(sum(response_counts)),
        "created_at": created_at,
        "seed": seed,
        "dataset": dataset_metadata,
        "synthetic": bool(dataset_metadata.get("synthetic", False)),
    }
    bundle = {
        "schema_version": MODEL_SCHEMA_VERSION,
        "base_feature_cols": list(BASE_FEATURE_COLS),
        "hand_feature_cols": list(HAND_FEATURE_COLS),
        "compatibility_feature_cols": list(COMPATIBILITY_FEATURE_COLS),
        "morphology_targets": list(MORPHOLOGY_TARGETS),
        "score_targets": list(SCORE_TARGETS),
        "normalization_stats": stats,
        "morphology_model": morphology_estimator,
        "score_model": score_estimator,
        "overall_weights": [float(value) for value in weights],
        "confidence_threshold": float(payload.get("confidenceThreshold") or 0.45),
        "cv_metrics": cv_metrics,
        "training_metadata": training_metadata,
        "feature_importance": {
            "morphology": top_feature_importance(morphology_estimator, HAND_FEATURE_COLS),
            "compatibility": top_feature_importance(score_estimator, COMPATIBILITY_FEATURE_COLS),
        },
        # Compatibility aliases for operational tooling that still expects a
        # generic model/feature_cols pair. Prediction dispatches by schema_version.
        "model": score_estimator,
        "feature_cols": list(COMPATIBILITY_FEATURE_COLS),
    }

    backup_path = backup_existing(output_path, payload)
    temporary_path = output_path.with_suffix(output_path.suffix + ".tmp")
    joblib.dump(bundle, temporary_path, compress=3)
    os.replace(temporary_path, output_path)

    overall_mae = float(cv_metrics.get("overall", {}).get("mae", 100.0))
    validation_score = max(0.0, min(100.0, 100.0 - overall_mae))
    result = {
        "schemaVersion": MODEL_SCHEMA_VERSION,
        "sampleCount": len(rows),
        "groupCount": int(len(np.unique(groups))),
        "questionnaireResponseCount": int(sum(response_counts)),
        "validationScore": round(validation_score, 2),
        "cvMetrics": cv_metrics,
        "overallWeights": {
            target: round(float(weights[index]), 6)
            for index, target in enumerate(SCORE_TARGETS)
        },
        "outputPath": str(output_path),
        "backupPath": backup_path,
        "featureCount": len(COMPATIBILITY_FEATURE_COLS),
        "createdAt": created_at,
        "synthetic": bool(dataset_metadata.get("synthetic", False)),
    }
    write_json(payload.get("reportPath"), result)
    print(json.dumps(result, ensure_ascii=False))


if __name__ == "__main__":
    main()
